doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            auth:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: Auth
            core:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Entity'
                prefix: 'App\Core\Infrastructure\Entity'
                alias: Core
            location:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Location/Entity'
                prefix: 'App\Location\Entity'
                alias: Location
            review:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Review/Infrastructure/Entity'
                prefix: 'App\Review\Infrastructure\Entity'
                alias: Review
            storage:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Storage/Entity'
                prefix: 'App\Storage\Entity'
                alias: Storage

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
