framework:
    messenger:
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
#             sync: 'sync://'

        routing:
            'App\Sms\Message\SmsMessage': async
            'App\Core\Message\Task\GenerateNextTaskMessage': async

when@test:
    framework:
        messenger:
            transports:
                async: 'test://'
#                sync: 'test://'
