version: "3.7"

services:
    php:
        build: &php-build
            context: .
        ports:
            - '6050:8000'
        volumes: &volumes
            - ./:/app/
            - ./docker/php/aliases:/root/.bashrc
        command: symfony server:start
        container_name: fastjob-php
        depends_on:
            - postgres
            - redis

    postgres:
        image: postgres:14.6-alpine
        container_name: fastjob-postgres
        ports:
            - '6060:5432'
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
        volumes:
          - postgres_data:/var/lib/postgresql/data:rw

    redis:
        image: redis:7.0.5-alpine
        restart: always
        volumes:
            - redis_data:/data
        container_name: fastjob-redis

    redis-test:
        image: redis:7.0.5-alpine
        restart: always
        container_name: fastjob-redis-test

    async-consumer:
        build: *php-build
        volumes: *volumes
        container_name: fastjob-async-consumer
        restart: always
        command: bin/console messenger:consume async --limit 10 -vv


volumes:
    postgres_data:
    redis_data:

