version: "3.7"

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./app:/app
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        container_name: fastjob-nginx
        restart: always
        depends_on:
            - php
        ports:
            - "6050:80"

    php:
        build: &php-build
            context: .
        volumes: &volumes
            - ./:/app/
            - ./docker/php/aliases:/root/.bashrc
        container_name: fastjob-php
        depends_on:
            - postgres
            - redis
            - mongodb

    postgres:
        image: postgres:14.6-alpine
        container_name: fastjob-postgres
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
        volumes:
          - postgres_data:/var/lib/postgresql/data:rw

    redis:
        image: redis:7.0.5-alpine
        restart: always
        volumes:
            - redis_data:/data
        container_name: fastjob-redis

    redis-test:
        image: redis:7.0.5-alpine
        restart: always
        container_name: fastjob-redis-test

    async-consumer:
        build: *php-build
        volumes: *volumes
        container_name: fastjob-async-consumer
        restart: always
        command: bin/console messenger:consume async --limit 10 -vv

    wiremock:
        image: wiremock/wiremock:2.35.0-alpine
        container_name: fastjob-wiremock
        restart: always

    mongodb:
        image: mongo
        container_name: fastjob-mongo
        volumes:
            - mongo_data:/data/db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 6060:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
        depends_on:
            - mongodb
        container_name: fastjob-mongo-express

#    caddy:
#        image: caddy:alpine
#        restart: unless-stopped
#        container_name: fastjob-caddy
#        volumes:
#            - ./config/Caddyfile:/etc/caddy/Caddyfile
#            - ./:/app
#        depends_on:
#            - php
#        ports:
#            - "6056:80"

volumes:
    postgres_data:
    redis_data:
    mongo_data:

