api:
    prefix: '/api'
    resource: ../../src/Api/Controller
    type: annotation

ping:
    resource: '../../src/Api/Controller/PingController.php'
    type: annotation

auth:
    prefix: '/auth-api'
    resource: '../../src/Api/Controller/Auth/AuthController.php'
    type: annotation

admin:
    resource: ../../src/Admin/Controller
    prefix: '/admin'
    type: annotation

storage:
    resource: ../../src/Api/Controller/Storage
    type: annotation
